/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculatron_extraction_PendingExtraction */

#ifndef _Included_com_calculatron_extraction_PendingExtraction
#define _Included_com_calculatron_extraction_PendingExtraction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calculatron_extraction_PendingExtraction
 * Method:    extract
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_calculatron_extraction_PendingExtraction_extract
  (JNIEnv *, jobject);

/*
 * Class:     com_calculatron_extraction_PendingExtraction
 * Method:    instaceNeocognitron
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_calculatron_extraction_PendingExtraction_instaceNeocognitron
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_calculatron_extraction_PendingExtraction
 * Method:    destroyNeocognitron
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_calculatron_extraction_PendingExtraction_destroyNeocognitron
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
