/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calculatron_extraction_PendingExtraction */

#ifndef _Included_com_calculatron_extraction_PendingExtraction
#define _Included_com_calculatron_extraction_PendingExtraction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calculatron_extraction_PendingExtraction
 * Method:    extract
 * Signature: ()Ljava/lang/String;
 */
//
JNIEXPORT void JNICALL Java_com_calculatron_extraction_PendingExtraction_extract(
		JNIEnv *, jobject);

// To set up
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM *vm, void *pvt);

// To clean up
JNIEXPORT void JNICALL JNI_OnUnload(JavaVM *vm, void *pvt);

#ifdef __cplusplus
}
#endif
#endif
